### PR TITLE
Return of results

### PR DESCRIPTION
**Pull request by tsibley**
Creating this PR to track review comments.

### CODE REVIEW

**Comment by tsibley** [comment]
Thanks for seeing this through! Overall looks great. Some notes, all relatively minor:

- [ ] On /results/barcode-faq, let's always show the answers instead of putting them behind disclosable elements. Text hidden behind disclosable elements, especially for short lists, is a usability anti-pattern. (I know Formative chose to do this for the main FAQ, which I also think is bad, but we're not the owners of that.) As a slightly bigger change, I think it'd be even better to put these questions and answers at the bottom of the /results page, right after the barcode input. It makes them immediately available and there's nothing else going there.
- [ ] On /results/barcode-faq and in the results footer, make the phone number a `tel:` link.
- [ ] On /results/barcode-faq, if it stays a separate page, I think it'd be nice to make this match the two-column layout of the main FAQ page.
- [ ] I think the text needs a good copy-editing pass in Contentful to make it consistent with regard to punctuation, italics, etc.
- [ ] The big blue blocks with centered text or indented lists don't look great on a phone. I suspect most folks will be using their phone to look up their results.

**Comment by misjailcisin** [comment]
With regard to copy-editing, I'm happy to do that, and can also have Maggie from formative give it a read through to make sure it matches the "tone" and everything else.

**Comment by trvrb** [comment]
Really excellent work here @joverlee521! Some issues:

1. The `/results/barcode-faq` page is an orphan. If I click on "Where do I find my barcode" I arrive here without an obvious way back. But generally I agree with @tsibley's point 1 above. It would be better if clicking "where do I find my barcode" either do a modal overlay or just unfold text at the bottom of the page.

2. The pure blue boxes with white text are unique to `/results`. These are intense display elements and I be more sparing with their use. Currently the page is:
* blue box: "disclaimer"
* white background: actual result
* blue box: hygiene recs
This is exactly flipped from what I would expect. The most important thing to show the user is their result. Disclaimer and hygiene recs are secondary. Also, the closest design element to this is the "join the study" box here: https://seattleflu-website-dev-blab.herokuapp.com/kiosks that uses a watercolor background. I find this less jarring and this then calls back to the splash page.

3. I'm getting errors on sample barcodes that I believe should work. For example `d6274d33` shows up as an encounter from Dec 2018 that's coronavirus positive. However, I get an "oops we don't have that barcode from the site".  Did you somehow restrict to just community enrollments?

**Comment by joverlee521** [comment]
> 3. I'm getting errors on sample barcodes that I believe should work. For example `d6274d33` shows up as an encounter from Dec 2018 that's coronavirus positive. However, I get an "oops we don't have that barcode from the site".  Did you somehow restrict to just community enrollments?

The results page expects the sample collection barcode, `d6274d33` seems to be the sample identifier barcode.

**Comment by joverlee521** [comment]
> 2. The pure blue boxes with white text are unique to `/results`. These are intense display elements and I be more sparing with their use. Currently the page is:
> 
> ```
> * blue box: "disclaimer"
> * white background: actual result
> * blue box: hygiene recs
> ```
> 
> This is exactly flipped from what I would expect. The most important thing to show the user is their result. Disclaimer and hygiene recs are secondary. Also, the closest design element to this is the "join the study" box here: https://seattleflu-website-dev-blab.herokuapp.com/kiosks that uses a watercolor background. I find this less jarring and this then calls back to the splash page.

@trvrb I do agree that the blue background jumps out a lot more, but I thought the actual results look more professional in black text on white background. 

It sounds like Formative will have their UX team to work on aligning the results page with the rest of the site, so I'll just leave it as is for now and let them handle it 😄

**Comment by trvrb** [comment]
Really nice work with this @joverlee521.

**Pull request merged**
